@startuml
class RestBehavior {
    + Name : string <<get>>
    + Priority : int <<get>>
    - _directionChangeTicks : int
    - _currentDirectionX : double
    - _currentDirectionY : double
    + CanExecute(animal:Animal) : bool
    + Execute(animal:Animal) : void
}
class "IBehavior`1"<T> {
}
"IBehavior`1" "<Animal>" <|-- RestBehavior
@enduml
