@startuml
class Algae {
    # _animationManager : IAnimationManager?
    + {static} DefaultMaxHealth : int <<get>>
    + {static} DefaultMaxEnergy : int <<get>>
    + <<override>> MaxHealth : int <<get>>
    + <<override>> MaxEnergy : int <<get>>
    # <<override>> BaseAbsorptionRate : double <<get>>
    + Algae(worldService:IWorldService, timeManager:ITimeManager, entityFactory:IEntityFactory, healthPoints:int, energy:int, position:Position)
    # <<override>> CanSpreadSeeds() : bool
    # <<override>> CreateOffspring(position:Position) : Plant
    # InitializeSprite(path:string, frameWidth:int, frameHeight:int) : void
    + UpdateAnimation(deltaTime:double) : void
}
Plant <|-- Algae
IAnimatable <|-- Algae
Algae --> "Sprite" AnimatedSprite
Algae --> "CurrentState" AnimationState
Algae --> "DefaultEnvironment" EnvironmentType
Algae --> "PreferredEnvironment" EnvironmentType
Algae --> "_entityFactory" IEntityFactory
@enduml
