@startuml
class MainWindowViewModel <<partial>> {
    - _status : string = "Ready"
    - _simulationSpeed : double = 1.0
    - _debug : bool = true
    + MainWindowViewModel(simulationEngine:ISimulationEngine, timeManager:ITimeManager, worldService:IWorldService)
    + InitializeAndStart() : void
    - StartSimulation() : void
    - PauseSimulation() : void
    - ResetSimulation() : void
    <<partial>> - OnSimulationSpeedChanged(value:double) : void
    - _windowWidth : double = 800
    - _windowHeight : double = 450
    <<partial>> - OnWindowWidthChanged(value:double) : void
    <<partial>> - OnWindowHeightChanged(value:double) : void
}
ViewModelBase <|-- MainWindowViewModel
MainWindowViewModel --> "_simulationEngine" ISimulationEngine
MainWindowViewModel --> "_timeManager" ITimeManager
MainWindowViewModel --> "_worldService" IWorldService
@enduml
