@startuml
class GroundHuntingStrategy {
    + GroundHuntingStrategy(worldService:IWorldService)
    + GetPotentialPrey(worldService:IWorldService, position:Position, visionRadius:double) : IEnumerable<Animal>
}
IHuntingStrategy <|-- GroundHuntingStrategy
GroundHuntingStrategy --> "_worldService" IWorldService
@enduml
