@startuml
interface IHuntingStrategy {
    CalculateAttackDamage(baseAttackPower:double) : int
    CalculateEnergyGain(baseAttackPower:double) : int
    GetPotentialPrey(worldService:IWorldService) : IEnumerable<Animal>
}
@enduml
