@startuml
class Shark {
    + <<override>> BaseAttackPower : double <<get>>
    # <<override>> BaseAttackRange : double <<get>>
    # <<override>> BaseHungerThreshold : double <<get>>
    # <<override>> BaseReproductionThreshold : double <<get>>
    # <<override>> BaseReproductionEnergyCost : double <<get>>
    # <<override>> SpeciesEnergyCostModifier : double <<get>>
    + Shark(entityLocator:IEntityLocator<Animal>, preyLocator:IEntityLocator<Animal>, worldService:IWorldService, timeManager:ITimeManager, healthPoints:int, energy:int, position:Position, isMale:bool)
    + <<override>> CreateOffspring(position:Position) : Animal
    # <<override>> GetEnvironmentMovementModifier() : double
}
Carnivore <|-- Shark
Shark --> "PreferredEnvironment" EnvironmentType
@enduml
