@startuml
class Shark {
    + {static} DefaultMaxHealth : int <<get>>
    + {static} DefaultMaxEnergy : int <<get>>
    + <<override>> MaxHealth : int <<get>>
    + <<override>> MaxEnergy : int <<get>>
    + <<override>> BaseAttackPower : double <<get>>
    # <<override>> BaseAttackRange : double <<get>>
    # <<override>> BaseBiteCooldownDuration : double <<get>>
    + <<override>> BaseHungerThreshold : double <<get>>
    # <<override>> BaseReproductionThreshold : double <<get>>
    # <<override>> BaseReproductionEnergyCost : double <<get>>
    # <<override>> SpeciesEnergyCostModifier : double <<get>>
    + GestationPeriod : double <<get>>
    + MaleReproductionCooldown : double <<get>>
    + FemaleReproductionCooldown : double <<get>>
    + Shark(entityLocator:IEntityLocator<Animal>, preyLocator:IEntityLocator<Animal>, worldService:IWorldService, timeManager:ITimeManager, entityFactory:IEntityFactory, position:Position, healthPoints:int, energy:int, isMale:bool)
    + <<override>> CreateOffspring(position:Position) : Animal
    + <<override>> UpdateAnimation(deltaTime:double) : void
}
Carnivore <|-- Shark
IReproductionConstants <|-- Shark
Shark --> "DefaultEnvironment" EnvironmentType
Shark --> "PreferredEnvironment" EnvironmentType
Shark --> "_entityFactory" IEntityFactory
@enduml
