@startuml
abstract class MoveableEntity {
    # BasalMetabolicRate : double <<get>>
    # {abstract} SpeciesEnergyCostModifier : double <<get>>
    # MoveableEntity(position:Position, healthPoints:int, energy:int, environment:EnvironmentType, basalMetabolicRate:double, timeManager:ITimeManager)
    + <<virtual>> MovementSpeed : double <<get>> <<protected set>>
    # <<virtual>> CalculateMovementEnergyCost(deltaX:double, deltaY:double) : int
    # _currentDirectionX : double = 0
    # _currentDirectionY : double = 0
    # _directionChangeTicks : int = 0
    - _accumulatedEnergyCost : double = 0
    + <<virtual>> Move(deltaX:double, deltaY:double) : void
    # <<virtual>> GetEnvironmentMovementModifier() : double
    + AddEnergy(amount:int) : void
    + RemoveEnergy(amount:int) : void
}
LifeForm <|-- MoveableEntity
IMoveable <|-- MoveableEntity
MoveableEntity --> "_timeManager" ITimeManager
@enduml
