@startuml
abstract class Entity {
    - _color : IBrush?
    - Position_PropertyChanged(sender:object?, e:PropertyChangedEventArgs) : void
    + GetDistanceTo(otherPosition:Position) : double
    - <<readonly>> _id : int
    + DisplayName : string <<get>>
    + TypeId : int <<get>>
    + <<virtual>> StatsText : string <<get>>
    # Entity(position:Position)
    + <<virtual>> Update() : void
    # <<virtual>> OnPropertyChanged(propertyName:string) : void
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
}
class "Dictionary`2"<T1,T2> {
}
INotifyPropertyChanged <|-- Entity
Entity o-> "_position" Position
Entity --> "Position" Position
Entity --> "Color" IBrush
Entity o-> "_typeCounters<Type,int>" "Dictionary`2"
Entity --> "Stats" EntityStats
@enduml
