@startuml
abstract class LifeForm {
    + HealthPoints : int <<get>> <<protected set>>
    + Energy : int <<get>> <<protected set>>
    + IsDead : bool <<get>>
    # LifeForm(position:Position, healthPoints:int, energy:int, environment:EnvironmentType)
    + <<override>> Update() : void
    # <<virtual>> GetCurrentBehavior() : IBehavior<LifeForm>?
    # <<virtual>> UpdateBehavior() : void
    + TakeDamage(amount:int) : void
    # ConsumeEnergy(amount:int) : void
    # {abstract} Die() : void
}
Entity <|-- LifeForm
LifeForm --> "Environment" EnvironmentType
@enduml
