@startuml
class Position {
    - _x : double
    - _y : double
    + X : double <<get>> <<set>>
    + Y : double <<get>> <<set>>
    + Position(x:double, y:double)
    - OnPropertyChanged(propertyName:string) : void
    +  <<event>> PropertyChanged : PropertyChangedEventHandler? 
}
INotifyPropertyChanged <|-- Position
@enduml
