@startuml
interface ISimulationEngine {
     <<event>> SimulationUpdated : EventHandler? 
    InitializeSimulation() : void
    CreateInitialEntities() : void
    UpdateSimulation() : void
}
class SimulationEngine {
    +  <<event>> SimulationUpdated : EventHandler? 
    + SimulationEngine(worldService:IWorldService, entityFactory:IEntityFactory, timeManager:ITimeManager)
    + InitializeSimulation() : void
    + CreateInitialEntities() : void
    - CreateAnimal(count:int, health:double, energy:double) : void
    - CreatePlants(count:int, health:double, energy:double) : void
    + UpdateSimulation() : void
}
ISimulationEngine <|-- SimulationEngine
SimulationEngine --> "_worldService" IWorldService
SimulationEngine --> "_entityFactory" IEntityFactory
SimulationEngine --> "_timeManager" ITimeManager
@enduml
