@startuml
interface ISimulationEngine {
     <<event>> SimulationUpdated : EventHandler? 
    InitializeSimulation() : void
    ResetSimulation() : void
    CreateInitialEntities() : void
    UpdateSimulation() : void
}
class SimulationEngine {
    +  <<event>> SimulationUpdated : EventHandler? 
    +  <<event>> SeedChanged : EventHandler<int>? 
    - <<readonly>> _updateLock : object
    + SimulationEngine(worldService:IWorldService, entityFactory:IEntityFactory, timeManager:ITimeManager)
    + InitializeSimulation() : void
    + ResetSimulation() : void
    + CreateInitialEntities() : void
    + UpdateSimulation() : void
}
ISimulationEngine <|-- SimulationEngine
SimulationEngine --> "_worldService" IWorldService
SimulationEngine --> "_entityFactory" IEntityFactory
SimulationEngine --> "_timeManager" ITimeManager
@enduml
