@startuml
interface IReproductionConstants {
    GestationPeriod : double <<get>>
    MaleReproductionCooldown : double <<get>>
    FemaleReproductionCooldown : double <<get>>
}
class BirthBehavior {
    + Name : string <<get>>
    + Priority : int <<get>>
    + CanExecute(animal:Animal) : bool
    + Execute(animal:Animal) : void
}
class "IBehavior`1"<T> {
}
"IBehavior`1" "<Animal>" <|-- BirthBehavior
@enduml
