@startuml
interface IReproducible {
    IsMale : bool <<get>>
    ReproductionEnergyCost : double <<get>>
    FindNearestMate() : Animal?
    Reproduce(partner:Animal) : void
    ContactRadius : double <<get>>
}
IReproducible --> "Position" Position
@enduml
