@startuml
interface IEntityManager {
    AddEntity(entity:Entity) : void
    RemoveEntity(entity:Entity) : void
    GetNearbyEntities(source:Entity, radius:double) : IEnumerable<T>
    Update() : void
}
@enduml
