@startuml
interface IEnvironmentSensitive {
    GetEnvironmentMovementModifier() : double
}
IEnvironmentSensitive --> "Environment" EnvironmentType
IEnvironmentSensitive --> "PreferredEnvironment" EnvironmentType
@enduml
