@startuml
class StaticSprite {
    + StaticSprite(imagePath:string)
    + GetSourceRect() : Rect
}
ISprite <|-- StaticSprite
StaticSprite --> "_image" Bitmap
StaticSprite --> "SpriteSheet" Bitmap
@enduml
