@startuml
class App <<partial>> {
    + <<override>> Initialize() : void
    - ConfigureServices() : IServiceProvider
    + <<override>> OnFrameworkInitializationCompleted() : void
    - DisableAvaloniaDataAnnotationValidation() : void
}
Application <|-- App
App --> "Services" IServiceProvider
@enduml
