@startuml
scale 0.1
!include .\\App.axaml.puml
!include .\\Program.puml
!include .\\ViewLocator.puml
!include .\\Configuration\EntityConfig.puml
!include .\\Configuration\SimulationConfig.puml
!include .\\Configuration\WorldConfig.puml
!include .\\Helpers\AssetHelper.puml
!include .\\Helpers\BoolToColorConverter.puml
!include .\\Helpers\BoolToValueConverter.puml
!include .\\Helpers\MathHelpers.puml
!include .\\Helpers\OffsetConverter.puml
!include .\\Helpers\RadiusConverter.puml
!include .\\Helpers\RandomHelper.puml
!include .\\Helpers\SafeAreaConverter.puml
!include .\\Helpers\TypeConverters.puml
!include .\\ViewModels\EntityViewModel.puml
!include .\\ViewModels\GridCellViewModel.puml
!include .\\ViewModels\MainWindowViewModel.puml
!include .\\ViewModels\ViewModelBase.puml
!include .\\Views\MainWindow.axaml.puml
!include .\\Models\Animation\AnimatedSprite.puml
!include .\\Models\Animation\AnimationManager.puml
!include .\\Models\Animation\AnimationState.puml
!include .\\Models\Animation\IAnimatable.puml
!include .\\Models\Animation\IAnimationEvent.puml
!include .\\Models\Animation\ISprite.puml
!include .\\Models\Animation\StaticSprite.puml
!include .\\Models\Core\Entity.puml
!include .\\Models\Core\LifeForm.puml
!include .\\Models\Core\Position.puml
!include .\\Models\Radius\IRange.puml
!include .\\Models\Stats\EntityStats.puml
!include .\\Models\Stats\INameable.puml
!include .\\Services\Factory\EntityFactory.puml
!include .\\Services\Simulation\GameLoop.puml
!include .\\Services\Simulation\SimulationConstants.puml
!include .\\Services\Simulation\SimulationEngine.puml
!include .\\Services\Simulation\TimeManager.puml
!include .\\Services\World\IEntityLocator.puml
!include .\\Services\World\WorldEntityLocator.puml
!include .\\Services\World\WorldService.puml
!include .\\Models\Behaviors\Base\IBehavior.puml
!include .\\Models\Behaviors\Base\RestBehavior.puml
!include .\\Models\Behaviors\Hunt\GroundHunting.puml
!include .\\Models\Behaviors\Hunt\Hunting.puml
!include .\\Models\Behaviors\Hunt\IHuntingStrategy.puml
!include .\\Models\Behaviors\Hunt\IPredator.puml
!include .\\Models\Behaviors\Movement\EnvironmentSeekingBehavior.puml
!include .\\Models\Behaviors\Movement\GroupMovement.puml
!include .\\Models\Behaviors\Movement\IMoveable.puml
!include .\\Models\Behaviors\Movement\MoveableEntity.puml
!include .\\Models\Behaviors\Movement\TerritorialMovement.puml
!include .\\Models\Behaviors\Reproduction\BirthBehavior.puml
!include .\\Models\Behaviors\Reproduction\PheromoneAttractedBehavior.puml
!include .\\Models\Behaviors\Reproduction\PheromoneEmittingBehavior.puml
!include .\\Models\Behaviors\Survival\FleeingBehavior.puml
!include .\\Models\Behaviors\Survival\HungerBehavior.puml
!include .\\Models\Behaviors\Survival\IFleeingEntity.puml
!include .\\Models\Behaviors\Survival\IVital.puml
!include .\\Models\Entities\Animals\Animal.puml
!include .\\Models\Entities\Environment\DigestionSystem.puml
!include .\\Models\Entities\Environment\EnvironmentBase.puml
!include .\\Models\Entities\Environment\EnvironmentType.puml
!include .\\Models\Entities\Environment\GridWorld.puml
!include .\\Models\Entities\Environment\IEnvironmentSensitive.puml
!include .\\Models\Entities\Environment\Meat.puml
!include .\\Models\Entities\Environment\OrganicWaste.puml
!include .\\Models\Entities\Plants\Algae.puml
!include .\\Models\Entities\Plants\Grass.puml
!include .\\Models\Entities\Plants\Plant.puml
!include .\\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\obj\Debug\net8.0\ecosystem.AssemblyInfo.puml
!include .\\Models\Entities\Animals\Carnivores\Carnivore.puml
!include .\\Models\Entities\Animals\Carnivores\Cheetah.puml
!include .\\Models\Entities\Animals\Carnivores\Fox.puml
!include .\\Models\Entities\Animals\Carnivores\Shark.puml
!include .\\Models\Entities\Animals\Herbivores\Antelope.puml
!include .\\Models\Entities\Animals\Herbivores\Duck.puml
!include .\\Models\Entities\Animals\Herbivores\Fish.puml
!include .\\Models\Entities\Animals\Herbivores\Herbivore.puml
!include .\\Models\Entities\Animals\Herbivores\Rabbit.puml
!include .\\Models\Entities\Animals\Herbivores\Sheep.puml
!include .\\Models\Entities\Animals\Herbivores\Squirrel.puml
@enduml
