@startuml
class RandomHelper <<static>> {
    - {static} <<readonly>> lockObject : object
    - {static} instance : Random?
    - <<const>> BORDER_MARGIN : double = 0.05
    - {static} _seed : int = 42
    + {static} Seed : int <<get>>
    + {static} Initialize(seedValue:int) : void
    + {static} NextDouble() : double
    + {static} GetRandomPositionInRadius(centerX:double, centerY:double, radius:double) : (double X, double Y)
    + {static} GetRandomPosition() : Position
    + {static} NextGaussian(mean:double, standardDeviation:double) : double
    + {static} GetRandomDirection() : (double X, double Y)
}
RandomHelper --> "Instance" Random
@enduml
