@startuml
class Rabbit {
    + {static} DefaultMaxHealth : int <<get>>
    + {static} DefaultMaxEnergy : int <<get>>
    + <<override>> MaxHealth : int <<get>>
    + <<override>> MaxEnergy : int <<get>>
    # <<override>> BaseBiteSize : int <<get>>
    # <<override>> BaseBiteCooldownDuration : double <<get>>
    + <<override>> BaseHungerThreshold : double <<get>>
    # <<override>> BaseReproductionThreshold : double <<get>>
    # <<override>> BaseReproductionEnergyCost : double <<get>>
    # <<override>> SpeciesEnergyCostModifier : double <<get>>
    + Rabbit(entityLocator:IEntityLocator<Animal>, plantLocator:IEntityLocator<Plant>, worldService:IWorldService, timeManager:ITimeManager, entityFactory:IEntityFactory, position:Position, healthPoints:int, energy:int, isMale:bool)
    + <<override>> CreateOffspring(position:Position) : Animal
}
Herbivore <|-- Rabbit
Rabbit --> "DefaultEnvironment" EnvironmentType
Rabbit --> "PreferredEnvironment" EnvironmentType
Rabbit --> "_entityFactory" IEntityFactory
@enduml
