@startuml
class Sheep {
    # <<override>> BaseBiteSize : int <<get>>
    # <<override>> BaseHungerThreshold : double <<get>>
    # <<override>> BaseReproductionThreshold : double <<get>>
    # <<override>> BaseReproductionEnergyCost : double <<get>>
    # <<override>> SpeciesEnergyCostModifier : double <<get>>
    + Sheep(entityLocator:IEntityLocator<Animal>, plantLocator:IEntityLocator<Plant>, worldService:IWorldService, timeManager:ITimeManager, position:Position, healthPoints:int, energy:int, isMale:bool)
    + <<override>> CreateOffspring(position:Position) : Animal
}
Herbivore <|-- Sheep
Sheep --> "PreferredEnvironment" EnvironmentType
@enduml
